#!/bin/sh
set -eu

usage() {
  cat <<'USAGE'
Usage: xcode_git_version.sh [options]

Generate Xcode version values from the current Git state.

Options:
  --repo PATH                 Git working tree to inspect. Default: current directory.
  --marketing-version VALUE   auto, existing, or an explicit X.Y.Z value. Default: auto.
  --require-clean             Fail when git status --porcelain is non-empty.
  --utc                       Format timestamps in UTC instead of local time.
  --write-info-plist PATH     Stamp version values into an Info.plist.
  --write-xcconfig PATH       Write Xcode build setting assignments.
  --format FORMAT             Output shell, xcconfig, or none. Default: shell.
  --help                      Show this help.

Version scheme:
  MARKETING_VERSION       YYYY.MM.DD, unless --marketing-version existing or explicit.
  CURRENT_PROJECT_VERSION YYYYMMDD.HHMMSS.TYPE

TYPE:
  3 clean main/master branch
  2 clean develop branch
  1 clean other branch
  0 dirty working tree

Environment overrides:
  JNX_FIXED_COMMIT_VERSION   Use this CURRENT_PROJECT_VERSION.
  JNX_FIXED_COMMIT_REVISION  Use this JNXCommitRevision. Default: fixed.
  JNX_FIXED_COMMIT_DATE      Use this JNXCommitDate. Default: 1970-01-01T00:00:00+0000.
  JNX_FIXED_MARKETING_VERSION Use this MARKETING_VERSION unless --marketing-version is explicit.
USAGE
}

repo="."
marketing_version_mode="auto"
require_clean="0"
use_utc="0"
write_info_plist=""
write_xcconfig=""
format="shell"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo)
      repo="${2:?missing value for --repo}"
      shift 2
      ;;
    --marketing-version)
      marketing_version_mode="${2:?missing value for --marketing-version}"
      shift 2
      ;;
    --require-clean)
      require_clean="1"
      shift
      ;;
    --utc)
      use_utc="1"
      shift
      ;;
    --write-info-plist)
      write_info_plist="${2:?missing value for --write-info-plist}"
      shift 2
      ;;
    --write-xcconfig)
      write_xcconfig="${2:?missing value for --write-xcconfig}"
      shift 2
      ;;
    --format)
      format="${2:?missing value for --format}"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      usage >&2
      exit 64
      ;;
  esac
done

case "$format" in
  shell|xcconfig|none)
    ;;
  *)
    echo "error: --format must be shell, xcconfig, or none" >&2
    exit 64
    ;;
esac

if [ "$marketing_version_mode" != "auto" ] && [ "$marketing_version_mode" != "existing" ]; then
  if ! printf '%s\n' "$marketing_version_mode" | grep -Eq '^[0-9]+[.][0-9]+[.][0-9]+$'; then
    echo "error: --marketing-version must be auto, existing, or X.Y.Z" >&2
    exit 64
  fi
fi

repo_root="$(git -C "$repo" rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$repo_root" ]; then
  echo "error: $repo is not inside a Git working tree" >&2
  exit 69
fi

gitc() {
  git -C "$repo_root" "$@"
}

epoch_format() {
  epoch="$1"
  pattern="$2"

  if [ "$use_utc" = "1" ]; then
    if TZ=UTC date -r "$epoch" +"$pattern" >/dev/null 2>&1; then
      TZ=UTC date -r "$epoch" +"$pattern"
    else
      TZ=UTC date -d "@$epoch" +"$pattern"
    fi
  else
    if date -r "$epoch" +"$pattern" >/dev/null 2>&1; then
      date -r "$epoch" +"$pattern"
    else
      date -d "@$epoch" +"$pattern"
    fi
  fi
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

plist_set_string_value() {
  plist="$1"
  key="$2"
  value="$3"

  if [ ! -f "$plist" ]; then
    echo "error: Info.plist not found: $plist" >&2
    exit 66
  fi

  plutil -replace "$key" -string "$value" "$plist" 2>/dev/null ||
    plutil -insert "$key" -string "$value" "$plist"
}

write_xcconfig_file() {
  path="$1"
  dir="$(dirname "$path")"
  mkdir -p "$dir"
  tmp="${path}.tmp.$$"

  {
    printf '// Generated by xcode_git_version.sh. Do not edit.\n'
    if [ "$marketing_version_mode" != "existing" ]; then
      printf 'MARKETING_VERSION = %s\n' "$marketing_version"
    fi
    printf 'CURRENT_PROJECT_VERSION = %s\n' "$commit_version"
    printf 'JNXBuildDate = %s\n' "$build_date"
    printf 'JNXCommitDate = %s\n' "$commit_date"
    printf 'JNXCommitRevision = %s\n' "$commit_revision"
    printf 'JNXCommitVersion = %s\n' "$commit_version"
    printf 'JNXGitBranch = %s\n' "$branch_name"
    printf 'JNXGitDirty = %s\n' "$dirty"
  } >"$tmp"

  mv "$tmp" "$path"
}

if [ "${JNX_FIXED_COMMIT_VERSION:-}" ]; then
  commit_revision="${JNX_FIXED_COMMIT_REVISION:-fixed}"
  commit_version="$JNX_FIXED_COMMIT_VERSION"
  commit_date="${JNX_FIXED_COMMIT_DATE:-1970-01-01T00:00:00+0000}"
  build_date="$commit_date"
  branch_name="${JNX_FIXED_GIT_BRANCH:-fixed}"
  dirty="0"
  version_epoch="$(date +%s)"
else
  git_short_revision="$(gitc log -1 --pretty='format:%h')"
  git_epoch="$(gitc log -1 --pretty='format:%ct')"
  dirty_output="$(gitc status --porcelain)"
  branch_name="$(gitc symbolic-ref --quiet --short HEAD 2>/dev/null || gitc rev-parse --short HEAD)"

  if [ -z "$dirty_output" ]; then
    dirty="0"
    version_epoch="$git_epoch"
    commit_revision="$git_short_revision"
    case "$branch_name" in
      main|master)
        commit_type="3"
        ;;
      develop)
        commit_type="2"
        ;;
      *)
        commit_type="1"
        ;;
    esac
  else
    dirty="1"
    version_epoch="$(date +%s)"
    commit_revision="${git_short_revision}M"
    commit_type="0"
  fi

  if [ "$require_clean" = "1" ] && [ "$dirty" = "1" ]; then
    echo "error: Git working tree is dirty" >&2
    exit 65
  fi

  commit_version="$(epoch_format "$version_epoch" "%Y%m%d.%H%M%S").$commit_type"
  commit_date="$(epoch_format "$git_epoch" "%Y-%m-%dT%H:%M:%S%z")"
  build_date="$(epoch_format "$(date +%s)" "%Y-%m-%dT%H:%M:%S%z")"
fi

case "$marketing_version_mode" in
  existing)
    marketing_version=""
    ;;
  auto)
    marketing_version="${JNX_FIXED_MARKETING_VERSION:-$(epoch_format "$version_epoch" "%Y.%m.%d")}"
    ;;
  *)
    marketing_version="$marketing_version_mode"
    ;;
esac

if [ -n "$write_info_plist" ]; then
  if [ "$marketing_version_mode" != "existing" ]; then
    plist_set_string_value "$write_info_plist" "CFBundleShortVersionString" "$marketing_version"
  fi
  plist_set_string_value "$write_info_plist" "CFBundleVersion" "$commit_version"
  plist_set_string_value "$write_info_plist" "JNXBuildDate" "$build_date"
  plist_set_string_value "$write_info_plist" "JNXCommitDate" "$commit_date"
  plist_set_string_value "$write_info_plist" "JNXCommitRevision" "$commit_revision"
  plist_set_string_value "$write_info_plist" "JNXCommitVersion" "$commit_version"
fi

if [ -n "$write_xcconfig" ]; then
  write_xcconfig_file "$write_xcconfig"
fi

case "$format" in
  shell)
    if [ "$marketing_version_mode" != "existing" ]; then
      printf 'export MARKETING_VERSION=%s\n' "$(shell_quote "$marketing_version")"
    fi
    printf 'export CURRENT_PROJECT_VERSION=%s\n' "$(shell_quote "$commit_version")"
    printf 'export JNXBuildDate=%s\n' "$(shell_quote "$build_date")"
    printf 'export JNXCommitDate=%s\n' "$(shell_quote "$commit_date")"
    printf 'export JNXCommitRevision=%s\n' "$(shell_quote "$commit_revision")"
    printf 'export JNXCommitVersion=%s\n' "$(shell_quote "$commit_version")"
    printf 'export JNXGitBranch=%s\n' "$(shell_quote "$branch_name")"
    printf 'export JNXGitDirty=%s\n' "$(shell_quote "$dirty")"
    ;;
  xcconfig)
    if [ "$marketing_version_mode" != "existing" ]; then
      printf 'MARKETING_VERSION = %s\n' "$marketing_version"
    fi
    printf 'CURRENT_PROJECT_VERSION = %s\n' "$commit_version"
    printf 'JNXBuildDate = %s\n' "$build_date"
    printf 'JNXCommitDate = %s\n' "$commit_date"
    printf 'JNXCommitRevision = %s\n' "$commit_revision"
    printf 'JNXCommitVersion = %s\n' "$commit_version"
    printf 'JNXGitBranch = %s\n' "$branch_name"
    printf 'JNXGitDirty = %s\n' "$dirty"
    ;;
  none)
    ;;
esac
